README.md
If I'm not wrong GetObjectAsync is no longer part of Akavache:
https://github.com/akavache/Akavache/search?utf8=%E2%9C%93&q=GetObjectAsync
The extension method also does not appear in the VS Object Browser.
It only seems to exist in the README.
=> Changed README to reflect GetObject

README.md
As of https://github.com/ericsink/SQLitePCL.raw/commit/1081160c1e5dc75eefab04dd1eb5cf825864aca7, SQLitePCL.raw creates an x86 and x64 folder in the app build output and switches to the appropriate SQLite library at runtime, so users of the .NET 4.5 platform can target AnyCPU
=> Update the SQlite instructions in the README for the .NET desktop platform

Akavache.Sqlite3/OperationQueue.cs, Akavache.Sqlite3/OperationQueueCoalescing.cs, Akavache.Sqlite3/Operations.cs, Akavache.Tests/BlobCacheExtensionsFixture.cs
Vacuum is broken in Akavache.Sqlite3 most likely going back to 4.0.0. There's two issues at play. 
One is that you can't have multiple statements in a prepared statement so the ```VACUUM``` statement was never been executed, only the ```DELETE```. Second, the ```VACUUM``` statement [can't be run within a transaction](https://sqlite.org/lang_vacuum.html) which is a problem since Akavache wraps everything in a transaction.
This is a first PoC solution which splits the vacuum operation into two statements that are run sequentially. Because of the transaction limitation we commit the transaction right the vacuum and then start it up again after. This will very likely have unintended side-effects but it's a proof that this is what's going on.
=> Fix vacuum

Akavache/Portable/BlobCache.cs
Fixes issue #192.
Adding a null "ShutdownBlobCache" that can be used to prevent caches that were never used from being created upon BlobCache.Shutdown().  I set a static bool when Shutdown is called, then add a check of that bool to the null coalescing chain before a new instance would be created.
Please be kind, this is my first pull request on any project EVER.
=> Prevents caches that were never used being created as side effect of BlobCache.Shutdown()

Akavache.Sqlite3/AsyncLock.cs, Akavache.Sqlite3/OperationQueue.cs, Akavache.Sqlite3/OperationQueueCoalescing.cs, Akavache.Sqlite3/Operations.cs, Akavache.Sqlite3/SqlitePersistentBlobCacheNext.cs, Akavache.Tests/Akavache.Tests.csproj, Akavache.Tests/AsyncLockTests.cs
There's two race conditions in Flush and Vacuum. They try to pre-empt the main queue by scheduling a DoNothing operation but does so before waiting on the lock and the lock itself has no guarantees on ordering. To demonstrate, add a delay between the scheduling and the lock wait.
This PR addresses that but while I was investigating I also found a bug in AsyncLock which is fixed in this PR. The AsyncLock in Akavache was improved upon from the original in the hanselman blog post by making it cancellable. Unfortunately the task returned from LockAsync would complete regardless of the lock acquisition being cancelled or not, leading to a SemaphoreFullException when the "lock" was released. It also made flushLock unreliable a shutdown scenario.
There's context and explanations hidden in the …
=> Fix deadlock in flush and vacuum

Akavache.Sqlite3/SqlitePersistentBlobCacheNext.cs, Akavache.Tests/BlobCacheFixture.cs, Akavache/Portable/BlobCache.cs, Akavache/Portable/InMemoryBlobCache.cs
JSON.NET's BSON infrastructure writes DateTimes as UTC and reads them back as Local. There is a configuration property for this, but it exists only on the reader and writer - JsonSerializerSettings does not affect it. This PR adds the ability for client code to force a particular setting on JsonReader.DateTimeKindHandling.
=> Allow UTC DateTimes to be forced.

Akavache.Sqlite3/OperationQueue.cs
This makes initial calls to e.g BlobCache.Get faster, because it doesn't
have to construct the SQLite operations that aren't even used when
selecting from the database
=> Lazily initialize the various SQLite operations

Akavache.Sqlite3/SqlitePersistentBlobCacheNext.cs
Makes GetAllKeys() and others 100x faster when storing multi MB blobs. This also creates the index on existing databases, so no need to migrate or recreate.
=> Added CacheElement.Expiration index

Akavache.Sqlite3/Akavache.Sqlite3.csproj, Akavache.Sqlite3/Akavache.Sqlite3.nuspec, Akavache.Sqlite3/SQLite.cs, Akavache.Sqlite3/packages.Akavache.Sqlite3.config, Akavache.Tests/Akavache.Tests.csproj, Akavache.Tests/packages.config
/cc @ghuntley @ericsink Can you review this please?
=> Update the SQLite dependency to support Android 7

README.md
Change "Ater" to "After".
Fix #340.
=> Fix a typo in README.md.

README.md
Documents ForcedDateTimeKind for reading back values.
Docs Update
Updated docs
No
Documents changes that took place in #255
=> Document BlobCache.ForcedDateTimeKind in README.md

src/Akavache.Sqlite3/SQLite.cs
Batteries.Init().  the new one does exactly the same thing, but supports bait-and-switch across bundle types, which eases difficulties that can happen when using multiple libraries that use SQLitePCL.raw.
bug fix (more or less)
call SQLitePCL.Batteries.Init()
call SQLitePCL.Batteries_V2.Init()
no
=> use SQLitePCL.Batteries_V2.Init() instead of the original 

src/Directory.build.targets
https://github.com/reactiveui/ReactiveUI/issues/1443
Min version defaults to unsupported version
Min version is now set to
<TargetPlatformMinVersion>10.0.10586.0</TargetPlatformMinVersion>
It shouldn't
=> set UWP min version to 10.0.10586.0

src/Akavache.Core/Akavache.Core.csproj, src/Akavache.Mobile/Akavache.Mobile.csproj, src/Akavache.Sqlite3/Akavache.Sqlite3.csproj, src/Akavache.Tests/Akavache.Tests.csproj
Refer to https://github.com/reactiveui/ReactiveUI/pull/1451 for backstory. 
Fixes https://github.com/reactiveui/ReactiveUI/pull/1413 by bypassing NuGet issue @ https://github.com/NuGet/Home/issues/5751
System.Reactive v4.x and NuGet.exe needs more time to mature. We can remove these restrictions as a point release at a later point in time. Dynamic data is currently using `3.1.1` as min but is not clamped @RolandPheasant I strongly recommend that you do the same changes. Similar changes will be applied to Akavache, Refit, Punchclock, etc.
=> fix: restrict system.reactive to 3.1.1 as min but never 4.x series

GitVersion.yml
This allows us to start shipping 6.0.0 to NuGet using the `alpha` prefix. This directive will be ignored after the tag/offical release of 6.0.0 (and should be removed)
=> housekeeping: bump next version to be 6.0

build.cake, build.cmd, src/Akavache.Sqlite3/Akavache.Sqlite3.csproj, src/Akavache.Sqlite3/content/AkavacheSqliteLinkerOverride.cs.pp, src/Akavache.Sqlite3/contentFiles/cs/any/AkavacheSqliteLinkerOverride.cs.pp, src/Akavache.sln
Added the content file back in for  SQLitePersistentBlobCache linker preservation
File wasn't included as content anaymore
The pp file is not included and gets added correctly into projects using older package.config structure
it shouldn't
=> adding content in for package.config nuget

src/Akavache.Sqlite3/OperationQueue.cs
Bug fix
See #406
Use `Task.Run` to start `OperationQueue`'s processing task rather than using the constructor and then calling `task.Start`. This ensures two things:
1. The `TaskScheduler.Default` scheduler is used, which will be a threadpool scheduler
2. That `task` tracks the running of the entire task: previously the task will have completed when it `await`ed as the `Task` constructor accepts an `Action` and not a `Func<Task>`
Note that `TaskCreationOptions.LongRunning` is no longer being passed in, but according to …
=> Use Task.Run to start OperationQueue.

src/Directory.build.props
Change from using the deprecated library to use the same one that Rx, RxUI use.
Use a deprecated library.
Use the use library which will put correct sourcelink data in.
Shouldn't.
=> Fix the SourceLink package to use Microsofts.

README.md
Somehow `GetObjectAsync` found it's way back in to the README.
=> Fix README typo: GetObjectAsync => GetObject

azure-pipelines.yml
the name of the environment variables was different between rxui and akavache, now using the correct ones to match.
=> fix: fix akavache build failing to sign

src/Akavache.Core/JsonDateTimeTickConverter.cs
Fix bug where datetime is stored as local and restored as UTC forgetting the offset.
stores 12:00 UTC+1
restores 12.00 UTC+0
stores 12:00 UTC+1
restores 11.00 UTC+0
No
=> Fix datetime tick storage

src/Akavache.Core/JsonDateTimeContractResolver.cs, src/Akavache.Tests/Akavache.Tests.csproj, src/Akavache.Tests/DateTimeTests.cs
fixes #463 
The problem was that, as the default ResolveContract() calls CreateContact(), in your CreateContact() you can't call ResolveContract() on the embedded contractResolver, as it will also (often) inherit from DefaultContractResolver.
So it loops.
I moved the code in ResolveContract instead, which make the issue disappear. It won't loop anymore!
I also check if the contract is already overriden by the other resolver. In this case let it handle the conversion.
No. …
=> fix infinite loop in new datetime converter, fixes issue #463

src/Akavache.Core/Akavache.Core.csproj, src/Akavache.Core/BlobCache/BlobCache.cs, src/Akavache.Core/BlobCache/InMemoryBlobCache.cs, src/Akavache.Core/DependencyResolverMixin.cs, src/Akavache.Core/IWantsToRegisterStuff.cs, src/Akavache.Core/KeyedOperations/KeyedOperationQueue.cs, src/Akavache.Core/Platforms/shared/Registrations.cs, src/Akavache.Core/Platforms/shared/Utility.cs, src/Akavache.Mobile/Registrations.cs, src/Akavache.Sqlite3/Akavache.Sqlite3.csproj, src/Akavache.Sqlite3/Operations/SqliteOperationMixin.cs, src/Akavache.Sqlite3/Registrations.cs, src/Akavache.Sqlite3/SqlLiteCache/SqlRawPersistentBlobCache.cs, src/Akavache.Tests/Akavache.Tests.csproj, src/Akavache/Registrations.cs
Upgrades Splat to v7.*
Splat is on v6.*
Splat is on v7.*
No.  It does change platform registrations for Akavache against Splat.
=> housekeeping: Update Splat v7.*

src/Akavache.Tests/Akavache.Tests.csproj, src/Akavache.Tests/xunit.runner.json
This is a way to fix the problems with the xunit tests running under net461 with SQLitePCLRaw 2.0.
An attempt to update the SQLitePCLRaw dependency to 2.0 caused problems with the xunit tests running under net461.  I've generally found xunit with .NET Framework to be problematic for SQLitePCLRaw.  Turning off shadowCopy has been an effective solution before.
See xunit/xunit#1198 for a bit more info.
The tests now run, on my machine anyway.
I hope not.
- [I don't know ] The …
=> turn off xunit shadowCopy

src/Akavache.Sqlite3/SqlLiteCache/SqlRawPersistentBlobCache.cs, src/Akavache.Tests/Akavache.Tests.csproj, src/Akavache.Tests/EncryptedSqliteBlobBulkExtensionsTest.cs, src/Akavache.Tests/SqliteBlobCacheBulkExtensionsTest.cs, src/Akavache.Tests/SqliteBlobCacheExtensionsTests.cs, src/Akavache.Tests/TestBases/BlobCacheExtensionsTestBase.cs
This fixes #470 and fixes #451 
Change the SQL raw class to support IObjectBulkBlobCache interface. Implement the bulk insertions.
=> feature: Add bulk inserts for sqlite

src/Akavache.Core/BlobCache/InMemoryBlobCache.cs, src/Akavache.Tests/TestBases/BlobCacheInterfaceTestBase.cs
Fix
Vacuum doesn't remove expired entries from the cache.
Vacuum will remove expired entries from the cache.
Nothing
=> Fix inversed Vacuum logic and add test

src/Akavache.Sqlite3/Queues/OperationQueue.cs, src/Akavache.Sqlite3/SqlLiteCache/SqlRawPersistentBlobCache.cs, src/Directory.build.props
Fixes the analyzers that fails and also upgrades Roslynator to 2.2.0
=> housekeeping: Upgrade to Roslynator analyzers 2.2.0

version.json
Release version 6.10 of Akavache.
This release includes a new assembly called Akavache.Drawing which handles bitmap operations.
If you need to support Splat's IBitmap include a reference to this assembly.
=> Release: Version 6.10 of Akavache

src/Akavache.Core/Akavache.Core.csproj, src/Akavache.Mobile/Akavache.Mobile.csproj, src/Akavache.Sqlite3/Akavache.Sqlite3.csproj, src/Akavache/Akavache.csproj
Removes a left over instance of `Splat.Drawing` from non-drawing related assemblies.
Also remove netcoreapp2.0 as users of these assemblies will use the .net standard 2.0 version.
=> Fix: Remove Splat.Drawing from Akavache.sqlite

src/Akavache.Drawing/Akavache.Drawing.csproj, src/Akavache.Drawing/Registrations.cs, src/Akavache.sln
Includes Akavache.Drawing in the .sln file
Adds netstandard2.0 the target frameworks for Akavache.Drawing
After the bitmap mixing were moved to Akavache.Drawing, they could no longer be used in a .NET Standard project.
For example, on macOS, the following warning would be raised:
```
[NU1701] Package 'Akavache.Drawing 6.10.2' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETStandard,Version=v2.1'. This package may not be fully compatible with your project.
```
Akavache.Drawing's targets …
=> Allow referencing Akavache.Drawing from NetStandard project

src/Akavache.Core/BlobCache/InMemoryBlobCache.cs, src/Akavache.Core/Json/JsonDateTimeContractResolver.cs, src/Akavache.Sqlite3/SqlLiteCache/SqlRawPersistentBlobCache.cs, src/Akavache.Tests/TestBases/DateTimeTestBase.cs, src/Akavache.Tests/UtilityTests.cs
Bug fix: #587 
For every single object that is serialized/deserialized, a new ContractResolver is created. This is a VERY expensive, reflection-heavy operation. Newtonsoft.Json is very clear that you should create and reuse a single ContractResolver.
I believe this is low-risk.
If anyone has an idea of how to test this, please let me know. It is an implementation detail of a private method. As a part of this, I also fixed a couple tests that didn't work on unix-based systems.
Note that this improves performance of bulk operations by up to 40x on my Mac, iOS, and Android …
=> Fix: Don't create new ContractResolver on every serialization/deserialization

nuget.config, src/Akavache.Core/Akavache.Core.csproj, src/Akavache.Core/BlobCache/BlobCache.cs, src/Akavache.Core/BlobCache/IObjectBlobCache.cs, src/Akavache.Core/HttpMixinExtensions.cs, src/Akavache.Drawing/Akavache.Drawing.csproj, src/Akavache.Drawing/BitmapImageMixin.cs, src/Akavache.Mobile/Registrations.cs, src/Akavache.Sqlite3/Akavache.Sqlite3.csproj, src/Akavache.Sqlite3/SqlLiteCache/SQLiteEncryptedBlobCache.cs, src/Akavache.Sqlite3/SqlLiteCache/SqlRawPersistentBlobCache.cs, src/Akavache.Tests/API/ApiApprovalTests.AkavacheCore.net461.approved.txt, src/Akavache.Tests/API/ApiApprovalTests.AkavacheCore.net5.0.approved.txt, src/Akavache.Tests/API/ApiApprovalTests.AkavacheCore.netcoreapp3.1.approved.txt, src/Akavache.Tests/Akavache.Tests.csproj, src/Akavache.Tests/TestBases/BlobCacheExtensionsTestBase.cs, src/Akavache.Tests/UtilityTests.cs, src/Directory.build.props
This PR updates nullability annotations in SQLite persistent blob cache, and picks dependabot deps.
=> housekeeping: Update nullability annotations

src/Akavache.Core/Akavache.Core.csproj, src/Akavache.CosmosDB/Akavache.CosmosDB.csproj, src/Akavache.Drawing/Akavache.Drawing.csproj, src/Akavache.Mobile/Akavache.Mobile.csproj, src/Akavache.Sqlite3/Akavache.Sqlite3.csproj, src/Akavache.Tests/API/ApiApprovalTests.AkavacheCore.netcoreapp3.1.approved.txt, src/Akavache.Tests/API/ApiApprovalTests.AkavacheProject.netcoreapp3.1.approved.txt, src/Akavache/Akavache.Sqlite3.BundleE.csproj, src/Akavache/Akavache.csproj, src/Directory.build.props, version.json
Fixes https://github.com/reactiveui/Akavache/issues/540
Fixes https://github.com/reactiveui/Akavache/issues/680
=> feature: Add netstandard2.1 and TVOS targets

.github/workflows/ci-build.yml, .github/workflows/release.yml, src/Akavache.Core/Akavache.Core.csproj, src/Akavache.Drawing/Akavache.Drawing.csproj, src/Akavache.Mobile/Akavache.Mobile.csproj, src/Akavache.Sqlite3/Akavache.Sqlite3.csproj, src/Akavache.Tests/API/ApiApprovalTests.AkavacheCore.net6.0.approved.txt, src/Akavache.Tests/API/ApiApprovalTests.AkavacheDrawing.net6.0.approved.txt, src/Akavache.Tests/API/ApiApprovalTests.AkavacheProject.net6.0.approved.txt, src/Akavache.Tests/Akavache.Tests.csproj, src/Akavache.sln, src/Akavache/Akavache.csproj, src/Directory.build.props, src/Directory.build.targets, version.json
Update
**What is the current behaviour?**
Old Targets
**What is the new behaviour?**
Remove MonoAndroid11.0
Remove MonoAndroid10.0
Add MonoAndroid12.0
Add MonoAndroid12.1
Add MonoAndroid13.0
Remove UWP
Add Net7.0
MonoAndroid10.0 and MonoAndroid11.0 removed
**Please check if the PR fulfils these requirements**
=> Housekeeping Remove Unsupported Targets

src/Akavache.Core/Akavache.Core.csproj, src/Akavache.Drawing/Akavache.Drawing.csproj, src/Akavache.Mobile/Akavache.Mobile.csproj, src/Akavache.Sqlite3/Akavache.Sqlite3.csproj, src/Akavache.Tests/API/ApiApprovalTests.AkavacheDrawing.net6.0.approved.txt, src/Akavache/Akavache.csproj, src/global.json, version.json
Update
Targets include Net 6.0 Android, ios, etc which are no longer supported
removed unsupported targets
those targeting net6.0-xxxx will need to update to net7.0-xxxx
=> Housekeeping Update Targets

src/Akavache.Core/BlobCache/BlobCache.cs, src/Akavache.Core/BlobCache/InMemoryBlobCache.cs, src/Akavache.Core/DependencyResolverMixin.cs, src/Akavache.Core/IWantsToRegisterStuff.cs, src/Akavache.Core/KeyedOperations/KeyedOperationQueue.cs, src/Akavache.Core/Platforms/android/AndroidFilesystemProvider.cs, src/Akavache.Core/Platforms/apple-common/MacFilesystemProvider.cs, src/Akavache.Core/Platforms/shared-not-uwp/SimpleFilesystemProvider.cs, src/Akavache.Core/Platforms/shared/AkavacheHttpMixin.cs, src/Akavache.Core/Platforms/shared/Registrations.cs, src/Akavache.Core/Platforms/shared/Utility.cs, src/Akavache.Core/Platforms/xamarin-mobile/IsolatedStorageProvider.cs, src/Akavache.Core/Providers/IFilesystemProvider.cs, src/Akavache.Drawing/Registrations.cs, src/Akavache.Mobile/AkavacheDriver.cs, src/Akavache.Mobile/Registrations.cs, src/Akavache.Sqlite3/Registrations.cs, src/Akavache.Sqlite3/SqlLiteCache/SQLiteEncryptedBlobCache.cs, src/Akavache.Sqlite3/SqlLiteCache/SqlRawPersistentBlobCache.cs, src/Akavache.Tests/API/ApiApprovalTests.AkavacheCore.DotNet8_0.verified.txt, src/Akavache.Tests/API/ApiApprovalTests.AkavacheDrawing.DotNet8_0.verified.txt, src/Akavache.Tests/API/ApiApprovalTests.AkavacheProject.DotNet8_0.verified.txt, src/Akavache.Tests/AsyncLockTests.cs, src/Akavache.Tests/CoalescerTests.cs, src/Akavache.Tests/TestBases/BulkOperationsTestBase.cs, src/Akavache/Registrations.cs, src/Akavache/SQLitePersistentBlobCache.cs, src/Directory.build.props
update
no AOT markup present
This pull request includes various changes to the `Akavache` project, primarily to add attributes for handling code analysis warnings and to update method implementations. The most important changes are grouped by theme below.
* Added `RequiresUnreferencedCode` and `RequiresDynamicCode` attributes for .NET 8.0 or greater in multiple files, including `BlobCache.cs`, `InMemoryBlobCache.cs`, `DependencyResolverMixin.cs`, `KeyedOperationQueue.cs`, `AndroidFilesystemProvider.cs`, `MacFilesystemProvider.cs`, `SimpleFilesystemProvider.cs`, `AkavacheHttpMixin.cs`, `Registrations.cs`, `Utility.cs`, `IsolatedStorageProvider.cs`, `IFilesystemProvider.cs`, …
=> Add AOT markup

LICENSE, src/Akavache.Core/Akavache.Core.csproj, src/Akavache.Drawing/Akavache.Drawing.csproj, src/Akavache.Mobile/Akavache.Mobile.csproj, src/Akavache.Sqlite3/Akavache.Sqlite3.csproj, src/Akavache.Sqlite3/SqlLiteCache/SqlRawPersistentBlobCache.cs, src/Akavache.Tests/API/ApiApprovalTests.AkavacheCore.DotNet8_0.verified.txt, src/Akavache.Tests/API/ApiApprovalTests.AkavacheCore.DotNet9_0.verified.txt, src/Akavache.Tests/API/ApiApprovalTests.AkavacheDrawing.DotNet9_0.verified.txt, src/Akavache.Tests/API/ApiApprovalTests.AkavacheDrawing.Net4_8.verified.txt, src/Akavache.Tests/API/ApiApprovalTests.AkavacheProject.DotNet9_0.verified.txt, src/Akavache.Tests/Akavache.Tests.csproj, src/Akavache.Tests/TestBases/BlobCacheExtensionsTestBase.cs, src/Akavache/Akavache.csproj, src/Directory.build.props
update
outdated packages with merge conflicts on update
This pull request includes several changes to update package references, improve code quality, and modify access levels for properties in the `Akavache` project. The most important changes are grouped below by theme.
* Updated `Newtonsoft.Json.Bson` to version `1.0.3` and `System.Security.Cryptography.ProtectedData` to version `9.0.3` in `src/Akavache.Core/Akavache.Core.csproj`. Added `Microsoft.NET.ILLink.Tasks` version `9.0.3` as a new package reference.
* Updated `Splat.Drawing` to version `15.3.1` and added `Microsoft.NET.ILLink.Tasks` version `9.0.3` in `src/Akavache.Drawing/Akavache.Drawing.csproj`.
* Added …
=> Update packages resolve conflicts

src/Akavache.Core/Akavache.Core.csproj, src/Akavache.Drawing/Akavache.Drawing.csproj, src/Akavache.Mobile/Akavache.Mobile.csproj, src/Akavache.Sqlite3/Akavache.Sqlite3.csproj, src/Akavache.Tests/API/ApiApprovalTests.AkavacheCore.DotNet9_0.verified.txt, src/Akavache.Tests/API/ApiApprovalTests.AkavacheDrawing.DotNet9_0.verified.txt, src/Akavache.Tests/API/ApiApprovalTests.AkavacheProject.DotNet9_0.verified.txt, src/Akavache.Tests/Akavache.Tests.csproj, src/Akavache/Akavache.csproj
Update
Packages failing to update due to breaking change
This pull request updates package dependencies across multiple project files to newer versions and adds annotations for dynamic and unreferenced code requirements in API approval tests. These changes enhance compatibility, maintainability, and clarity in code analysis.
* Updated `System.Security.Cryptography.ProtectedData` and `Microsoft.NET.ILLink.Tasks` to version `9.0.6` in `Akavache.Core`, `Akavache.Drawing`, `Akavache.Mobile`, `Akavache.Sqlite3`, and `Akavache` projects. [[1]](diffhunk://#diff-c53de64c92ba8a4ac6ef5d091bd87bf495459fd36b57afb2fe170b96fc0bf844L17-R18) …
=> Housekeeping Update packages after breaking change

src/Akavache.Benchmarks/CacheDatabaseReadBenchmarks.cs, src/Akavache.Core/BlobCache.cs, src/Akavache.Core/BlobCacheBuilder.cs, src/Akavache.Core/IBlobCacheBuilder.cs, src/Akavache.Drawing/Size.cs, src/Akavache.EncryptedSqlite3/Akavache.EncryptedSqlite3.csproj, src/Akavache.Sqlite3/BlobCacheBuilderExtensions.cs, src/Akavache.Sqlite3/Registrations.cs
feature
With Akavache versions <= 10 a Splat magic registration approach is taken
Version 11 will introduce the option to use a Builder approach due to the number of options that can exist.
This pull request introduces significant updates to the Akavache library, focusing on a new builder-based configuration system for `BlobCache`, improvements to code maintainability, and minor refactoring in benchmark files. Below are the most important changes grouped by theme:
* Introduced a new `BlobCache` class with a builder-based configuration system, allowing flexible initialization and management of cache instances (`InMemory`, `LocalMachine`, `Secure`, `UserAccount`). This includes …
=> Introduce builder pattern for BlobCache configuration

src/Akavache.Core/AkavacheBuilderExtensions.cs, src/Akavache.Core/CacheDatabase.cs, src/Akavache.Core/Core/AkavacheBuilder.cs, src/Akavache.Core/Core/FileLocationOption.cs, src/Akavache.Core/IAkavacheBuilder.cs, src/Akavache.Sqlite3/AkavacheBuilderExtensions.cs
update
Legacy file paths are not included
Introduces the FileLocationOption enum to allow selection between default and legacy cache directory locations. Updates AkavacheBuilder, IAkavacheBuilder, and related initialization methods to support this option. Adjusts cache directory resolution logic in both core and Sqlite3 extensions to respect the selected file location option.
Defaults to V11 file locations
=> Add Legacy FileLocationOption for cache directory selection
