Akavache/Portable/BulkOperationsMixin.cs
Akavache/Portable/JsonSerializationMixin.cs

InsertAllObjects self recursion

---

Akavache/akavache.nuspec

Pin the Splat dependency in the nuspec file to the same version we're building Akavache with

---

Akavache.Sqlite3/SqlitePersistentBlobCacheNext.cs

Index the TypeName in the database to make bulk object queries faster

---

README.md

Add some words about the all-important `Shutdown()` method.

Add Shutdown docs to README.

---

Akavache.Sqlite3/Akavache.Sqlite3.nuspec

Source:
https://github.com/ericsink/SQLitePCL.raw#theres-another-nuget-package-called-sqlitepclraw_basic--what-is-it
Fixes https://github.com/akavache/Akavache/issues/257

Use the non-deprecated SQLite.raw package and update it to version 0.8.6 to support UWP

---

README.md

Added documentation for which storage to choose when

---

README.md

Fix documentation clarity on what `BlobCache.UserAccount` do

docs: add clarification to the info on UserAccount

---

src/Akavache.Core/Akavache.Core.csproj
src/Akavache.Mobile/Akavache.Mobile.csproj
src/Akavache.Sqlite3/Akavache.Sqlite3.csproj
src/Akavache.Tests/Akavache.Tests.csproj

Updated the System.Reactive and the ReactiveUI/ReactiveUITests dependencies

Updated System.Reactive to 4.0.0 from 3.1.1

---

src/Akavache.Core/Akavache.Core.csproj
src/Akavache.Mobile/Akavache.Mobile.csproj
src/Akavache.Sqlite3/Akavache.Sqlite3.csproj
src/Akavache.Tests/Akavache.Tests.csproj
src/Akavache.sln
src/Akavache/Akavache.csproj
src/Directory.build.props
src/Directory.build.targets
src/global.json

Update sdk extras to the latest format plus a few house keeping items

update to latest sdk extras structures

---

src/Akavache.Core/Akavache.Core.csproj
src/Akavache.Core/DependencyResolverMixin.cs
src/Akavache.Core/Platforms/shared/Registrations.cs
src/Akavache.Core/PreserveAttribute.cs
src/Akavache.Core/Properties/AssemblyInfo.cs
src/Akavache.Mobile/Registrations.cs
src/Akavache.Sqlite3/Akavache.Sqlite3.csproj
src/Akavache.Sqlite3/Registrations.cs
src/Akavache.Sqlite3/SQLite.cs
src/Akavache.Sqlite3/SQLiteEncryptedBlobCache.cs
src/Akavache.Sqlite3/SqlLiteCache.cs
src/Akavache.Sqlite3/SqlitePersistentBlobCacheNext.cs
src/Akavache.Sqlite3/content/AkavacheSqliteLinkerOverride.cs.pp
src/Akavache.Sqlite3/contentFiles/cs/any/AkavacheSqliteLinkerOverride.cs.pp
src/Akavache.Tests/Akavache.Tests.csproj
src/Akavache.Tests/BlobCacheExtensionsFixture.cs
src/Akavache.Tests/BlobCacheFixture.cs
src/Akavache.Tests/BulkOperationsTest.cs
src/Akavache.Tests/Performance/ReadTests.cs
src/Akavache.Tests/Performance/WriteTests.cs
src/Akavache/Akavache.csproj
src/Akavache/AkavacheSqliteLinkerOverride.cs
src/Akavache/Properties/AssemblyInfo.cs
src/Akavache/Registrations.cs
src/Akavache/SQLitePersistentBlobCache.cs

feature
Mainly creating this PR to get visibility into my first implementation of letting users install Akavache pieces and thus use their own raw provider
https://github.com/akavache/Akavache/issues/380
Moved the bundle dependency into Akavache package so someone could just add the core/sqlite3 packges
It shouldn't  I tried to structure it so existing "LinkerOverrides" would still work every one involved

Initial sql raw implementation

---

src/Akavache.Sqlite3/Akavache.Sqlite3.csproj
src/Akavache.Tests/Akavache.Tests.csproj
src/Akavache/Akavache.csproj

housekeeping: Update to SQLitePCLRaw v1.1.12

---

src/Akavache.Core/JsonDateTimeContractResolver.cs
src/Akavache.Core/JsonDateTimeOffsetTickConverter.cs
src/Akavache.Core/JsonDateTimeTickConverter.cs
src/Akavache.Tests/DateTimeTests.cs

Additional fix to comments in #269

housekeeping: store the DateTimeOffset ticks and offset.

---

src/Akavache.Tests/Akavache.Tests.csproj

Remove unnecessary nuget package.

housekeeping: Remove unneeded PackageReference

---

CODE_OF_CONDUCT.md
README.md
src/Directory.build.props

NA - Non-functional change
NA - Non-functional change
NA - Non-functional change
NA - Non-functional change
NA - Non-functional change

Housekeeping: Updated URL and Email references to Anaïs Betts

---

src/Akavache.Core/Akavache.Core.csproj
src/Akavache.Mobile/Akavache.Mobile.csproj
src/Akavache.Sqlite3/Akavache.Sqlite3.csproj
src/Akavache/Akavache.csproj

Fixes build issues with MonoAndroid
Build is broken.
Build is not broken
The already broken build

fix: Android issue with MsBuild.Sdk.Extras

---

build.cake
build.config
src/Akavache.Core/Akavache.Core.csproj
src/Akavache.Sqlite3/Akavache.Sqlite3.csproj
src/Akavache.Sqlite3/Operations/BulkInvalidateSqliteOperation.cs
src/Akavache.Sqlite3/Operations/BulkSelectSqliteOperation.cs
src/Akavache.Tests/Akavache.Tests.csproj
src/Akavache/Registrations.cs
src/Directory.build.props
src/global.json
tests/NuGetInstallationIntegrationTests/Android/Resources/Resource.Designer.cs
version.json

housekeeping: Update to Splat 9.*

---

README.md

This fixes #531 and makes it more obvious where the registration call has to be made.

housekeeping: Update instructions for the Registration

---

src/Akavache.Drawing/Registrations.cs

Fix: issue with namespace conflict

---

README.md
src/Directory.build.props

Akavache logo is updated with the new image from the [styleguide repository](https://github.com/reactiveui/styleguide).
Planning to update `Directory.Build.props` to use the new image as well soon.
Nothing.

Use the new logo image

---

README.md

Docs update
This PR will hide the full doc links currently visible in the readme.
Also updated the UWP link to bypass the auto-redirect.

Hide raw links.

---

README.md

This PR adds a TOC to the readme and reorders the content. The goal is to provide an overview and make the content easier to follow.
Some markdownlint violations were also resolved.
TOC's are easy to add and update via the [Markdown All in One](https://marketplace.visualstudio.com/items?itemName=yzhang.markdown-all-in-one) VS Code extension. Just install and run:
* Markdown All In One: Create Table of Contents
* Markdown All In One: Update Table of Contents
The Toc: Levels extension setting for this readme as set to `2..3`
Also recommended is the [Github Markdown Preview extension](https://marketplace.visualstudio.com/items?itemName=bierner.github-markdown-preview) and …

Add a TOC to readme & reorder content.

---

src/Akavache.Core/BlobCache/InMemoryBlobCache.cs
src/Akavache.Sqlite3/SqlLiteCache/SqlRawPersistentBlobCache.cs

Bug fix
When registering a JsonSerializerSettings with the Splat Locator as a singleton (which is probably the most common scenario), all subsequent calls to store/retrieve something from the cache will inadvertently create another nested ContractResolver, eventually resulting in a stack overflow. This was actually an issue before my PR earlier today, but I should have seen it then.
The old behavior was also weird because it changed the ContractResolver in whatever JsonSerializerSettings you registered (if it is a singleton). That would be pretty unexpected if you relied on those settings from something outside of Akavache.
Restore the ContractResolver in the …

Fix circular reference when serializing/deserializing after registering a singleton JsonSerializerSettings with the Locator

---

README.md

Update the icons for the readme file.

housekeeping: Update the readme icons

---

version.json

Releases 7.1.x which contains a number of fixes and the first pass at nullability support.

housekeeping: Release 7.1.x

---

src/Akavache.Tests/API/ApiApprovalTests.cs
src/Akavache.Tests/Akavache.Tests.csproj

Fix
using an older version of Verify.Xunit
using latest version of Verify.Xunit
updated test to suit new version
none

Fix for Verify.Xunit update

---

.github/workflows/ci-build.yml
.github/workflows/release.yml

Housekeeping Update Build

---

src/Akavache.Core/Akavache.Core.csproj
src/Akavache.Drawing/Akavache.Drawing.csproj
src/Akavache.Mobile/Akavache.Mobile.csproj
src/Akavache.Tests/Akavache.Tests.csproj

Update
ReactiveUI and Splat packages updated to latest

Update ReactiveUI and Splat to latest

---

src/Akavache.Tests/Akavache.Tests.csproj
src/Akavache/Akavache.csproj
src/Directory.build.props
version.json

Update
Update Version due to breaking change in DynamicData

Housekeeping Update Version

---

README.md

docs
Improves documentation for resolving SQLite errors on mobile by providing XML-based package reference examples. Adds instructions for preserving assemblies to prevent linker issues, and updates code samples to reflect correct type names.
N/A

Update README with SQLite and linker guidance
